# Generated by Django 4.0.1 on 2022-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'ordering': ['name'], 'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_date',
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Наименование категории товаров'),
        ),
    ]
